A Library of MSP430 C Code: FIFO Ring Buffer
FIFO Ring Buffer
FIFO Ring Buffer.
Detailed Description
FIFO Ring Buffer.
Author
Alex Mykyta
This module creates a generic First-in First-out ring buffer.
Data Structures
struct FIFO_t
Functions
void fifo_init (FIFO_t *fifo, void *bufptr, size_t bufsize)
Initializes a new FIFO Ring Buffer.
RES_t fifo_write (FIFO_t *fifo, void *src, size_t size)
Write data into the FIFO buffer.
void fifo_write_trample (FIFO_t *fifo, void *src, size_t size)
Write data into the FIFO buffer. Tramples over oldest unread data if necessary.
RES_t fifo_read (FIFO_t *fifo, void *dst, size_t size)
Read data from the FIFO buffer.
size_t fifo_read_max (FIFO_t *fifo, void *dst, size_t max_size)
Read as much data from the FIFO buffer as possible.
RES_t fifo_peek (FIFO_t *fifo, void *dst, size_t size)
Read data from the FIFO buffer without advancing the read pointer.
void fifo_clear (FIFO_t *fifo)
Empties the FIFO.
size_t fifo_rdcount (FIFO_t *fifo)
Get the number of bytes available for read in the FIFO.
size_t fifo_wrcount (FIFO_t *fifo)
Get the number of bytes that can be written to the FIFO.
Files
file fifo.c
Code for FIFO Ring Buffer.
file fifo.h
Include file for FIFO Ring Buffer.
Function Documentation
fifo_clear()
void fifo_clear (FIFO_t * fifo)
Empties the FIFO.
Parameters
[in] fifo Pointer to the FIFO_t object
Returns
Nothing
References ATOMIC_BLOCK, and ATOMIC_RESTORESTATE.
fifo_init()
void fifo_init (FIFO_t * fifo, void * bufptr, size_t bufsize)
Initializes a new FIFO Ring Buffer.
Parameters
[in] bufptr Pointer to the buffer to be used as storage for the FIFO
[in] bufsize Size of the buffer in bytes
[in] fifo Pointer to an empty FIFO_t object
[out] fifo Initialized FIFO object
Returns
Nothing
fifo_peek()
RES_t fifo_peek (FIFO_t * fifo, void * dst, size_t size)
Read data from the FIFO buffer without advancing the read pointer.
Parameters
[in] fifo Pointer to the FIFO_t object
[out] dst Destination of the data to be read.
[in] size Number of bytes to be read from the FIFO
Return values
RES_OK
RES_PARAMERR Not enough bytes written in FIFO for requested read operation
References ATOMIC_BLOCK, ATOMIC_RESTORESTATE, fifo_rdcount(), RES_OK, and RES_PARAMERR.
fifo_rdcount()
size_t fifo_rdcount (FIFO_t * fifo)
Get the number of bytes available for read in the FIFO.
Parameters
[in] fifo Pointer to the FIFO_t object
Returns
Number of bytes
References ATOMIC_BLOCK, and ATOMIC_RESTORESTATE.
fifo_read()
RES_t fifo_read (FIFO_t * fifo, void * dst, size_t size)
Read data from the FIFO buffer.
Parameters
[in] fifo Pointer to the FIFO_t object
[out] dst Destination of the data to be read. A NULL pointer discards the data.
[in] size Number of bytes to be read from the FIFO
Return values
RES_OK
RES_PARAMERR Not enough bytes written in FIFO for requested read operation
References ATOMIC_BLOCK, ATOMIC_RESTORESTATE, fifo_rdcount(), RES_OK, and RES_PARAMERR.
fifo_read_max()
size_t fifo_read_max (FIFO_t * fifo, void * dst, size_t max_size)
Read as much data from the FIFO buffer as possible.
Parameters
[in] fifo Pointer to the FIFO_t object
[out] dst Destination of the data to be read. A NULL pointer discards the data.
[in] max_size Maximum number of bytes to be read from the FIFO
Returns
Number of bytes read
References ATOMIC_BLOCK, ATOMIC_RESTORESTATE, and fifo_rdcount().
fifo_wrcount()
size_t fifo_wrcount (FIFO_t * fifo)
Get the number of bytes that can be written to the FIFO.
Parameters
[in] fifo Pointer to the FIFO_t object
Returns
Number of bytes
References ATOMIC_BLOCK, and ATOMIC_RESTORESTATE.
fifo_write()
RES_t fifo_write (FIFO_t * fifo, void * src, size_t size)
Write data into the FIFO buffer.
Parameters
[in] fifo Pointer to the FIFO_t object
[in] src Pointer to the data to be stored
[in] size Number of bytes to be written to the FIFO
Return values
RES_OK
RES_FULL Not enough space in FIFO for requested write operation
References ATOMIC_BLOCK, ATOMIC_RESTORESTATE, fifo_rdcount(), fifo_wrcount(), RES_FULL, and RES_OK.
fifo_write_trample()
void fifo_write_trample (FIFO_t * fifo, void * src, size_t size)
Write data into the FIFO buffer. Tramples over oldest unread data if necessary.
Parameters
[in] fifo Pointer to the FIFO_t object
[in] src Pointer to the data to be stored
[in] size Number of bytes to be written to the FIFO
References ATOMIC_BLOCK, ATOMIC_RESTORESTATE, and fifo_wrcount().