A Library of MSP430 C Code: UART IO
UART IO
Provides basic text IO functions for the MSP430 UART controller.
Detailed Description
Provides basic text IO functions for the MSP430 UART controller.
Author
Alex Mykyta
This module provides basic text input and output functions to the UART.
MSP430 Processor Families Supported:
Family Supported
1xx Yes
2xx Yes
4xx Yes
5xx Yes
6xx Yes
Functions
void uart_init (void)
Initializes the UART controller.
void uart_uninit (void)
Uninitializes the UART controller.
void uart_read (void *buf, size_t size)
Read data from the UART. Blocks until all data has been received.
size_t uart_rdcount (void)
Get the number of bytes available to be read.
void uart_rdflush (void)
Discard any data that has already been received.
char uart_getc (void)
Reads the next character from the UART.
char * uart_gets_s (char *str, size_t n)
Reads in a string of characters until a new-line character (\n) is received.
void uart_write (void *buf, size_t size)
Write data to the UART. Blocks until all data has been sent.
void uart_putc (char c)
Writes a character to the UART.
void uart_puts (char *s)
Writes a character string to the UART.
void uart_rx_dma_isr (void)
UART RX DMA Interrupt Service Routine.
bool is_uart_rx_dma_isr (void)
Test to check if the current DMA ISR is for the uart_rx DMA.
Files
file uart_io.c
Code for UART IO.
file uart_io.h
Include file for UART IO.
file uart_io_config.TEMPLATE.h
Configuration include file for UART IO.
file uart_io_internal.h
Internal include for UART IO. Abstracts register names between MSP430 devices.
Configuration
Configuration defines for the UART IO module
#define UIO_RX_MODE 0
#define UIO_RXBUF_SIZE
#define UIO_RX_DMA_CHANNEL 0
#define RX_DMA_TSEL
#define UIO_TX_MODE 0
#define UIO_TXBUF_SIZE
#define UIO_USE_DEV
Select which USCI/USART module to use.
#define UIO_CLK_SRC
Select which clock source to use.
#define USART_BR0_VALUE 0x00
#define USART_BR1_VALUE 0x00
#define USART_MCTL_VALUE 0x00
#define USCI_BR0_VALUE 0x00
#define USCI_BR1_VALUE 0x00
#define USCI_MCTL_VALUE 0x00
#define EUSCI_BR0_VALUE 0x00
#define EUSCI_BR1_VALUE 0x00
#define EUSCI_MCTL_VALUE 0x0000
Macro Definition Documentation
UIO_CLK_SRC
#define UIO_CLK_SRC
Select which clock source to use.
0 = External
1 = ACLK
2 = SMCLK
UIO_RX_MODE
#define UIO_RX_MODE 0
0 = Polling Mode : No buffers used. RX is done directly by polling within function calls.
1 = Interrupt Mode : RX triggers an interrupt and data is pushed into a FIFO.
2 = DMA Mode : RX data is automatically loaded into a buffer using DMA.
UIO_TX_MODE
#define UIO_TX_MODE 0
0 = Polling Mode : No buffers used. TX functions will block until data is transmitted.
1 = Interrupt Mode : TX data is buffered. TX operations are handled using interrupts.
UIO_USE_DEV
#define UIO_USE_DEV
Select which USCI/USART module to use.
0 = USCIA0
1 = USCIA1
2 = USCIA2
3 = USCIA3
Function Documentation
is_uart_rx_dma_isr()
bool is_uart_rx_dma_isr (void)
Test to check if the current DMA ISR is for the uart_rx DMA.
Return values
true Interrupt flag corresponding to the UART RX DMA channel.
false RX DMA interrupt flag is not set.
uart_getc()
char uart_getc (void)
Reads the next character from the UART.
If a character is not immediately available, function will block until it receives one.
Returns
The next available character
References uart_read().
uart_gets_s()
char * uart_gets_s (char * str, size_t n)
Reads in a string of characters until a new-line character (\n) is received.
Reads at most n-1 characters from the UART
Resulting string is null-terminated
If n is zero, a null character is written to str[0], and the function reads and discards characters until a new-line character is received.
If n-1 characters have been read, the function continues reading and discarding characters until a new-line character is received.
If an entire line is not immediately available, the function will block until it receives a new-line character.
Parameters
[out] str Pointer to the destination string buffer
n The size of the string buffer str
Returns
str on success. NULL otherwise
uart_init()
void uart_init (void)
Initializes the UART controller.
Attention
The initialization routine does not setup the IO ports!
References fifo_init(), and UIO_CLK_SRC.
uart_putc()
void uart_putc (char c)
Writes a character to the UART.
Parameters
c character to be written
References uart_write().
uart_puts()
void uart_puts (char * s)
Writes a character string to the UART.
Parameters
s Pointer to the Null-terminated string to be sent
References is_uart_rx_dma_isr(), and uart_write().
uart_rdcount()
size_t uart_rdcount (void)
Get the number of bytes available to be read.
Returns
Number of bytes
References fifo_rdcount().
uart_read()
void uart_read (void * buf, size_t size)
Read data from the UART. Blocks until all data has been received.
Parameters
[out] buf Destination buffer of the data to be read. A NULL pointer discards the data.
[in] size Number of bytes to be read.
References fifo_rdcount(), and fifo_read().
uart_rx_dma_isr()
void uart_rx_dma_isr (void)
UART RX DMA Interrupt Service Routine.
If the UART RX mode is set to use DMA, the user must implement the DMA controller's ISR function. The ISR must call this function if the interrupt is for the RX DMA channel. This can be done using the is_uart_rx_dma_isr() function as follows:
if(is_uart_rx_dma_isr()){
    uart_rx_dma_isr();
}
uart_write()
void uart_write (void * buf, size_t size)
Write data to the UART. Blocks until all data has been sent.
Parameters
[in] buf Pointer to the data to be written.
[in] size Number of bytes to be written.
References fifo_wrcount(), and fifo_write().