A Library of MSP430 C Code: SPI Flash
SPI Flash
Interface driver for most SPI Flash devices.
Detailed Description
Interface driver for most SPI Flash devices.
Author
Alex Mykyta
Macros
#define SR_BUSY 0x01
#define SR_WEL 0x02
#define SR_BP0 0x04
#define SR_BP1 0x08
#define SR_BP2 0x10
#define SR_BP3 0x20
#define CMD_RD 0x03
#define CMD_ERASE4k 0x20
#define CMD_ERASE32k 0x52
#define CMD_ERASE64k 0xD8
#define CMD_CHIPERASE 0x60
#define CMD_WRAAI 0xAD
#define CMD_RDSR 0x05
#define CMD_WRSR 0x01
#define CMD_WREN 0x06
#define CMD_WRDI 0x04
#define CMD_JEDECID 0x9F
#define CMD_EBSY 0x70
#define CMD_DBSY 0x80
#define CMD_EN4B 0xB7
#define CMD_EX4B 0xE9
#define CMD_DP 0xB9
#define CMD_RDP 0xAB
#define ADDR_BYTES 3
#define PHYSICAL_ADDR(addr) (addr)
Functions
RES_t spi_flash_init (void)
Initializes the array of SPI flash devices.
void spi_flash_uninit (void)
Uninitializes the array of SPI flash devices.
RES_t spi_flash_read (uint32_t address, void *dst, uint16_t nBytes)
Read data from the spi flash volume.
RES_t spi_flash_write (uint32_t address, const void *src, uint16_t nBytes)
Write data to the spi flash volume.
RES_t spi_flash_4k_erase (uint32_t address)
Initiates an erase of a 4k region.
RES_t spi_flash_32k_erase (uint32_t address)
Initiates an erase of a 32k region.
RES_t spi_flash_64k_erase (uint32_t address)
Initiates an erase of a 64k region.
void spi_flash_bulk_erase (void)
Initiates a bulk erase the entire flash volume.
bool spi_flash_erase_busy (void)
Determines if an erase operation is in progress.
void spi_flash_seq_wr_start (uint32_t address)
Initiates a sequential write operation.
void spi_flash_seq_wr (const void *src, uint16_t nBytes)
Reads data sequentially.
void spi_flash_seq_wr_byte (uint8_t b)
Writes the next byte in a sequential write operation.
void spi_flash_seq_wr_end (void)
Terminates a sequential write operation.
void spi_flash_seq_rd_start (uint32_t address)
Initiates a sequential read operation.
void spi_flash_seq_rd (void *dst, uint16_t nBytes)
Reads data sequentially.
uint8_t spi_flash_seq_rd_byte (void)
Reads the next byte in a sequential read operation.
void spi_flash_seq_rd_end (void)
Terminates a sequential read operation.
uint32_t spi_flash_size (void)
Get the size of the flash array in bytes.
Files
file spi_flash.c
Code for SPI Flash.
file spi_flash.h
Include file for SPI Flash.
file spi_flash_config.TEMPLATE.h
Configuration include file for SPI Flash.
Configuration
Configuration defines for the SPI Flash module
#define CE_POUT P1OUT
#define CE_DEV_BITMAP {BIT6, BIT7}
#define CE_DEV_BITMASK (BIT6|BIT7)
#define DEVICE_COUNT 2
#define MISO_DIR_PORT P2DIR
#define MISO_IN_PORT P2IN
#define MISO_IN_PIN BIT0
#define F_CPU 1000000UL
#define DEVICE_ID 0x000000L
#define DEVICE_SIZE 0x1000L
#define DEVICE_HAS_DEEP_POWER_DOWN 1
Function Documentation
spi_flash_32k_erase()
RES_t spi_flash_32k_erase (uint32_t address)
Initiates an erase of a 32k region.
Determine if the operation is complete by polling spi_flash_erase_busy()
Parameters
[in] address Address within the erase region
Return values
RES_OK
RES_PARAMERR Invalid address
spi_flash_4k_erase()
RES_t spi_flash_4k_erase (uint32_t address)
Initiates an erase of a 4k region.
Determine if the operation is complete by polling spi_flash_erase_busy()
Parameters
[in] address Address within the erase region
Return values
RES_OK
RES_PARAMERR Invalid address
spi_flash_64k_erase()
RES_t spi_flash_64k_erase (uint32_t address)
Initiates an erase of a 64k region.
Determine if the operation is complete by polling spi_flash_erase_busy()
Parameters
[in] address Address within the erase region
Return values
RES_OK
RES_PARAMERR Invalid address
spi_flash_bulk_erase()
void spi_flash_bulk_erase (void)
Initiates a bulk erase the entire flash volume.
Warning
On some devices this can take several minutes. Determine if the operation is complete by polling spi_flash_erase_busy()
spi_flash_init()
RES_t spi_flash_init (void)
Initializes the array of SPI flash devices.
Return values
RES_OK
RES_FAIL
Attention
The initialization routine does not setup the IO ports!
spi_flash_read()
RES_t spi_flash_read (uint32_t address, void * dst, uint16_t nBytes)
Read data from the spi flash volume.
Parameters
address Start address of read operation
nBytes Number of bytes to be read
[out] dst Destination buffer
Return values
RES_OK
RES_PARAMERR Invalid address range
spi_flash_seq_rd()
void spi_flash_seq_rd (void * dst, uint16_t nBytes)
Reads data sequentially.
Parameters
nBytes Number of bytes to be read
[out] dst Destination buffer
References spi_rx_frame().
spi_flash_seq_rd_byte()
uint8_t spi_flash_seq_rd_byte (void)
Reads the next byte in a sequential read operation.
Returns
byte
References spi_transfer_byte().
spi_flash_seq_rd_start()
void spi_flash_seq_rd_start (uint32_t address)
Initiates a sequential read operation.
Sequential accesses are intended for situations where data will be read from flash sequentially but bulk buffer transfers are not practical. A sequential read must be initiated using spi_flash_seq_rd_start(). Following this, multiple calls to spi_flash_seq_rd_byte() or spi_flash_seq_rd() can be made to read a stream of data. The operation must be terminated using spi_flash_seq_rd_end().
Warning
Sequential accesses will not automatically roll over to the next SPI device in the array! These functions are intended to be lightweight and do not check address bounds!
Parameters
address start address
spi_flash_seq_wr()
void spi_flash_seq_wr (const void * src, uint16_t nBytes)
Reads data sequentially.
Parameters
nBytes Number of bytes to be written
[in] src Data to be written
References spi_flash_seq_wr_byte().
spi_flash_seq_wr_byte()
void spi_flash_seq_wr_byte (uint8_t b)
Writes the next byte in a sequential write operation.
Parameters
b Byte to be written
spi_flash_seq_wr_start()
void spi_flash_seq_wr_start (uint32_t address)
Initiates a sequential write operation.
Sequential accesses are intended for situations where data will be written to flash sequentially but bulk buffer transfers are not practical. A sequential write must be initiated using spi_flash_seq_wr_start(). Following this, multiple calls to spi_flash_seq_wr_byte() or spi_flash_seq_wr() can be made to write a stream of data. The operation must be terminated using spi_flash_seq_wr_end().
Warning
Sequential accesses will not automatically roll over to the next SPI device in the array! These functions are intended to be lightweight and do not check address bounds!
Parameters
address start address
spi_flash_size()
uint32_t spi_flash_size (void)
Get the size of the flash array in bytes.
Returns
number of bytes
spi_flash_write()
RES_t spi_flash_write (uint32_t address, const void * src, uint16_t nBytes)
Write data to the spi flash volume.
Note
Writing a multiple of 2 bytes at a time and aligned to an even address is recommended
Parameters
address Start address of write operation
nBytes Number of bytes to be written
[in] src Data to be written
Return values
RES_OK
RES_PARAMERR Invalid address range