A Library of MSP430 C Code: Event Queue
Event Queue
A simple first-in first-out event handler.
Detailed Description
A simple first-in first-out event handler.
Author
Alex Mykyta
Template main.c using the Event Queue
#include <msp430_xc.h>
#include <event_queue.h>
int main(void){
    WDTCTL = WDTPW + WDTHOLD; // Stop the Watchdog Timer
    __disable_interrupt(); // Disable Interrupts
    // Initialize Port IO
    ...
    // Initialize the system's clocks
    ...
    // Initialize the event handler
    event_init();
    // Initialize any modules that generate events
    ...
    // Turn on interrupts
    __enable_interrupt();
    // Start the event handler
    event_StartHandler();
    // Program never reaches this
    return(0);
}
void onIdle(void){
    // onIdle is called when no events occur.
    // To save power, the CPU can be put into a sleep state here.
}
Event Queue also requires the following modules:
FIFO Ring Buffer
Functions
void event_StartHandler (void)
Starts the event handler.
void event_init (void)
Initializes the event handler's queue.
RES_t event_PushEvent (void(*fptr)(void), void *eventData, size_t size)
Schedule a function to be called in the event queue along with related data.
void event_PopEventData (void *dst, size_t size)
Pop event-related data out of the event queue.
void event_YieldEvent (void)
Yields execution of the current event to the next pending event in the queue.
bool event_Pending (void)
Returns /c true if an event is in the queue.
Files
file event_queue.c
Code for Event Queue.
file event_queue.h
Include file for Event Queue.
file event_queue_config.TEMPLATE.h
Configuration include file for Event Queue.
Events
void onIdle (void)
Idle process event.
Configuration
Configuration for the Event Queue module
#define EVENT_QUEUE_SIZE
Number of bytes to reserve for the event queue.
#define MAX_YIELD_DEPTH
Maximum number of yielded event levels.
Function Documentation
event_init()
void event_init (void)
Initializes the event handler's queue.
This function must be called prior to starting the event handler
References fifo_init().
event_Pending()
bool event_Pending (void)
Returns /c true if an event is in the queue.
Return values
true An event is in the queue
false The event queue is empty
References fifo_rdcount().
event_PopEventData()
void event_PopEventData (void * dst, size_t size)
Pop event-related data out of the event queue.
Parameters
[in] dst Pointer to where the data will be read into
[in] size Number of bytes to be read
Use this function inside the event function scheduled by event_PushEvent()to retreive any related event data that was pushed in using event_PushEventData()
References fifo_read().
event_PushEvent()
RES_t event_PushEvent (void(*)(void) fptr, void * eventData, size_t size)
Schedule a function to be called in the event queue along with related data.
Parameters
[in] fptr Pointer to the function to be called
[in] eventData Pointer to the data to be pushed into the queue (If not used, enter NULL)
[in] size Number of bytes to be pushed (if none required, use size of 0)
Return values
RES_OK Event added successfully
RES_FULL Not enough room in the event queue. Event was not added.
The function to be called must not take any input parameters nor can it return any values. If pusing additional data with the event, the event called MUST have a matching event_PopEventData(). Every additional byte pushed into the event queue MUST be popped out regardless if it is used or not.
References fifo_wrcount(), fifo_write(), RES_FULL, and RES_OK.
event_StartHandler()
void event_StartHandler (void)
Starts the event handler.
After initializing the system after a reset and initializing the event module, Call this function to start the scheduler. This routine does not return.
Note
Global interrupts should be enabled prior to starting the handler
References fifo_rdcount(), and fifo_read().
event_YieldEvent()
void event_YieldEvent (void)
Yields execution of the current event to the next pending event in the queue.
Calling this function allows the next event in the queue to be executed. If no events are in the queue or the next event is already active, the onIdle() event is processed.
event_YieldEvent() can be called occasionally when performing a time-consuming operation within an event such as a polling loop. Doing so allows other events that may have piled up in the meantime to be processed.
onIdle()
void onIdle (void)
Idle process event.
This event is called repeatedly when there are no events pending.
NOTE: As with any other event, a new event cannot be called until the current one exits.