A Library of MSP430 C Code: Flash File System
Flash File System
Light-weight file system optimized for SPI Flash.
Detailed Description
Light-weight file system optimized for SPI Flash.
Author
Alex Mykyta
Data Structures
struct ffs_file_t
struct ffs_dir_t
struct ffs_file_info_t
Macros
#define MAX_FILENAME_LEN 32
Typedefs
typedef uint16_t block_idx_t
Enumerations
enum ffs_filemode_t {
FFS_CLOSED = 0,
FFS_RD,
FFS_WR_APPEND,
FFS_WR_REPLACE
}
Files
file flash_fs.h
Include file for Flash File System.
Filesystem operations
RES_t ffs_init (void)
Initializes the filesystem and the flash hardware.
void ffs_uninit (void)
Uninitializes the filesystem and the flash hardware.
uint16_t ffs_blocks_free (void)
Returns the number of unused blocks.
File Operations
RES_t ffs_fopen (ffs_file_t *f, const char *filename, ffs_filemode_t filemode)
Opens a file for reading or writing.
void ffs_fclose (ffs_file_t *f)
Closes the file.
void ffs_remove (const char *filename)
Deletes a file by name.
void ffs_opendir (ffs_dir_t *dir)
Initializes a directory object to start seeking through existing files.
bool ffs_readdir (ffs_dir_t *dir, ffs_file_info_t *info)
Read the next file in the directory.
uint32_t ffs_ftell (ffs_file_t *f)
Returns the current byte offset from the beginning of the file.
Read mode functions
size_t ffs_fread (void *data, size_t size, ffs_file_t *f)
Reads data from the file.
RES_t ffs_fseek (ffs_file_t *f, uint32_t offset)
Seeks to the specified byte offset from the beginning of the file.
bool ffs_feof (ffs_file_t *f)
Checks if the end of the given file has been reached.
Write mode functions
size_t ffs_fwrite (const void *data, size_t size, ffs_file_t *f)
Writes data to the file.
Enumeration Type Documentation
ffs_filemode_t
enum ffs_filemode_t
Enumerator
FFS_CLOSED
File is not open (Used internally)
FFS_RD
Open file for reading.
FFS_WR_APPEND
Open file for writing. Appends data. Creates new file if needed.
FFS_WR_REPLACE
Open file for writing. Replaces file. Creates new file if needed.
Function Documentation
ffs_blocks_free()
uint16_t ffs_blocks_free (void)
Returns the number of unused blocks.
Returns
Number of free blocks
ffs_fclose()
void ffs_fclose (ffs_file_t * f)
Closes the file.
Parameters
f Pointer to the file object
References FFS_CLOSED.
ffs_feof()
bool ffs_feof (ffs_file_t * f)
Checks if the end of the given file has been reached.
Note
This function only reports the state as reported by the most recent I/O operation, it does not examine the data source. For example, if the most recent I/O was a single byte read, which returned the last byte of the file, feof returns false. The next read fails and changes the state to end-of-file. Only then feof returns true.
Parameters
f Pointer to the file object
Return values
true Reached the end of the file
false Read pointer is not at the end of the file
ffs_fopen()
RES_t ffs_fopen (ffs_file_t * f, const char * filename, ffs_filemode_t filemode)
Opens a file for reading or writing.
Parameters
f Pointer to the file object
filename File name string
filemode Mode to open the file (See ffs_filemode_t)
Return values
RES_FULL Storage medium is full (write)
RES_NOTFOUND File not found (read)
RES_OK Success!
ffs_fread()
size_t ffs_fread (void * data, size_t size, ffs_file_t * f)
Reads data from the file.
Parameters
f Pointer to the file object
data Pointer to destination buffer
size Number of bytes to read from file
Returns
Number of bytes successfully read
References FFS_RD, spi_flash_read(), spi_flash_seq_rd_byte(), spi_flash_seq_rd_end(), and spi_flash_seq_rd_start().
ffs_fseek()
RES_t ffs_fseek (ffs_file_t * f, uint32_t offset)
Seeks to the specified byte offset from the beginning of the file.
For read files only!
Parameters
f Pointer to the file object
offset Number of bytes from the beginning of the file
Return values
RES_PARAMERR Invalid input parameter
RES_END Requested offset is greater than the file length. Seek is set to EOF.
RES_OK Success!
References FFS_RD, RES_END, RES_OK, RES_PARAMERR, spi_flash_read(), spi_flash_seq_rd_byte(), spi_flash_seq_rd_end(), and spi_flash_seq_rd_start().
ffs_ftell()
uint32_t ffs_ftell (ffs_file_t * f)
Returns the current byte offset from the beginning of the file.
Parameters
f Pointer to the file object
Returns
Byte offset from the beginning of the file
ffs_fwrite()
size_t ffs_fwrite (const void * data, size_t size, ffs_file_t * f)
Writes data to the file.
Parameters
f Pointer to the file object
data Pointer to source data
size Number of bytes to write to the file
Returns
Number of bytes successfully written
References FFS_WR_APPEND, FFS_WR_REPLACE, spi_flash_seq_wr(), spi_flash_seq_wr_byte(), spi_flash_seq_wr_end(), and spi_flash_seq_wr_start().
ffs_init()
RES_t ffs_init (void)
Initializes the filesystem and the flash hardware.
Return values
RES_FAIL Initialization of the storage medium failed
RES_INVALID Initialized flash, but no valid filesystem is present. Bulk erase the memory and try again (see spi_flash_bulk_erase())
RES_OK Success!
RES_FAIL Initialization of the storage medium failed
RES_INVALID Initialized flash, but no valid filesystem is present. Bulk erase the memory and format the flash before trying again (see spi_flash_bulk_erase() and ffs_create_filesystem())
RES_OK Success!
References RES_FAIL, RES_OK, spi_flash_init(), spi_flash_seq_rd(), spi_flash_seq_rd_end(), spi_flash_seq_rd_start(), and spi_flash_write().
ffs_opendir()
void ffs_opendir (ffs_dir_t * dir)
Initializes a directory object to start seeking through existing files.
Parameters
dir pointer to the directory object to be initialized
ffs_readdir()
bool ffs_readdir (ffs_dir_t * dir, ffs_file_info_t * info)
Read the next file in the directory.
Parameters
dir pointer to the directory object
info File info
Returns
true if info object is valid. false if reached the end of the directory.
References spi_flash_read(), spi_flash_seq_rd(), spi_flash_seq_rd_end(), and spi_flash_seq_rd_start().
ffs_remove()
void ffs_remove (const char * filename)
Deletes a file by name.
Parameters
filename File name string