A Library of MSP430 C Code: Extended String Functions
Extended String Functions
Additional string functions.
Detailed Description
Additional string functions.
Author
Alex Mykyta
Functions
uint8_t snprint_x8 (char *buffer, size_t buf_size, uint8_t num)
Converts an 8-bit integer into a hexadecimal string.
uint8_t snprint_x16 (char *buffer, size_t buf_size, uint16_t num)
Converts a 16-bit integer into a hexadecimal string.
uint8_t snprint_x32 (char *buffer, size_t buf_size, uint32_t num)
Converts a 32-bit integer into a hexadecimal string.
uint8_t snprint_d8 (char *buffer, size_t buf_size, uint8_t num)
Converts an unsigned 8-bit integer into a decimal string.
uint8_t snprint_d16 (char *buffer, size_t buf_size, uint16_t num)
Converts an unsigned 16-bit integer into a decimal string.
uint8_t snprint_d32 (char *buffer, size_t buf_size, uint32_t num)
Converts an unsigned 32-bit integer into a decimal string.
uint8_t snprint_sd8 (char *buffer, size_t buf_size, int8_t num)
Converts a signed 8-bit integer into a decimal string.
uint8_t snprint_sd16 (char *buffer, size_t buf_size, int16_t num)
Converts a signed 16-bit integer into a decimal string.
uint8_t snprint_sd32 (char *buffer, size_t buf_size, int32_t num)
Converts a signed 32-bit integer into a decimal string.
Files
file string_ext.c
Code for Extended String Functions.
file string_ext.h
Include file for Extended String Functions.
Function Documentation
snprint_d16()
uint8_t snprint_d16 (char * buffer, size_t buf_size, uint16_t num)
Converts an unsigned 16-bit integer into a decimal string.
Parameters
[out] buffer Pointer to a character string to write to. Outputs null-terminated string
[in] buf_size Up to buf_size - 1 characters may be written, plus the null terminator
[in] num Integer to be converted
Returns
Number of characters written if successful. If the resulting string gets truncated due to buf_size limit, function returns the total number of characters (not including the terminating null-byte) which would have been written, if the limit was not imposed.
snprint_d32()
uint8_t snprint_d32 (char * buffer, size_t buf_size, uint32_t num)
Converts an unsigned 32-bit integer into a decimal string.
Parameters
[out] buffer Pointer to a character string to write to. Outputs null-terminated string
[in] buf_size Up to buf_size - 1 characters may be written, plus the null terminator
[in] num Integer to be converted
Returns
Number of characters written if successful. If the resulting string gets truncated due to buf_size limit, function returns the total number of characters (not including the terminating null-byte) which would have been written, if the limit was not imposed.
snprint_d8()
uint8_t snprint_d8 (char * buffer, size_t buf_size, uint8_t num)
Converts an unsigned 8-bit integer into a decimal string.
Parameters
[out] buffer Pointer to a character string to write to. Outputs null-terminated string
[in] buf_size Up to buf_size - 1 characters may be written, plus the null terminator
[in] num Integer to be converted
Returns
Number of characters written if successful. If the resulting string gets truncated due to buf_size limit, function returns the total number of characters (not including the terminating null-byte) which would have been written, if the limit was not imposed.
snprint_sd16()
uint8_t snprint_sd16 (char * buffer, size_t buf_size, int16_t num)
Converts a signed 16-bit integer into a decimal string.
Parameters
[out] buffer Pointer to a character string to write to. Outputs null-terminated string
[in] buf_size Up to buf_size - 1 characters may be written, plus the null terminator
[in] num Integer to be converted
Returns
Number of characters written if successful. If the resulting string gets truncated due to buf_size limit, function returns the total number of characters (not including the terminating null-byte) which would have been written, if the limit was not imposed.
References snprint_d16().
snprint_sd32()
uint8_t snprint_sd32 (char * buffer, size_t buf_size, int32_t num)
Converts a signed 32-bit integer into a decimal string.
Parameters
[out] buffer Pointer to a character string to write to. Outputs null-terminated string
[in] buf_size Up to buf_size - 1 characters may be written, plus the null terminator
[in] num Integer to be converted
Returns
Number of characters written if successful. If the resulting string gets truncated due to buf_size limit, function returns the total number of characters (not including the terminating null-byte) which would have been written, if the limit was not imposed.
References snprint_d32().
snprint_sd8()
uint8_t snprint_sd8 (char * buffer, size_t buf_size, int8_t num)
Converts a signed 8-bit integer into a decimal string.
Parameters
[out] buffer Pointer to a character string to write to. Outputs null-terminated string
[in] buf_size Up to buf_size - 1 characters may be written, plus the null terminator
[in] num Integer to be converted
Returns
Number of characters written if successful. If the resulting string gets truncated due to buf_size limit, function returns the total number of characters (not including the terminating null-byte) which would have been written, if the limit was not imposed.
References snprint_d8().
snprint_x16()
uint8_t snprint_x16 (char * buffer, size_t buf_size, uint16_t num)
Converts a 16-bit integer into a hexadecimal string.
Parameters
[out] buffer Pointer to a character string to write to. Outputs null-terminated string
[in] buf_size Up to buf_size - 1 characters may be written, plus the null terminator
[in] num Integer to be converted
Returns
Number of characters written if successful. If the resulting string gets truncated due to buf_size limit, function returns the total number of characters (not including the terminating null-byte) which would have been written, if the limit was not imposed.
snprint_x32()
uint8_t snprint_x32 (char * buffer, size_t buf_size, uint32_t num)
Converts a 32-bit integer into a hexadecimal string.
Parameters
[out] buffer Pointer to a character string to write to. Outputs null-terminated string
[in] buf_size Up to buf_size - 1 characters may be written, plus the null terminator
[in] num Integer to be converted
Returns
Number of characters written if successful. If the resulting string gets truncated due to buf_size limit, function returns the total number of characters (not including the terminating null-byte) which would have been written, if the limit was not imposed.
snprint_x8()
uint8_t snprint_x8 (char * buffer, size_t buf_size, uint8_t num)
Converts an 8-bit integer into a hexadecimal string.
Parameters
[out] buffer Pointer to a character string to write to. Outputs null-terminated string
[in] buf_size Up to buf_size - 1 characters may be written, plus the null terminator
[in] num Integer to be converted
Returns
Number of characters written if successful. If the resulting string gets truncated due to buf_size limit, function returns the total number of characters (not including the terminating null-byte) which would have been written, if the limit was not imposed.